-- ═══════════════════════════════════════════════════════════════
-- ClientFlow CRM — Custom Auth & Staff Keys Update
-- ═══════════════════════════════════════════════════════════════

-- 1. STAFF KEYS TABLE
-- This table stores the 6-digit keys generated by Admin for staff login
CREATE TABLE IF NOT EXISTS public.staff_keys (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    key         text UNIQUE NOT NULL CHECK (length(key) = 6),
    role        text NOT NULL CHECK (role IN ('Manager', 'Customer Success', 'Sales Agent', 'Sales Closer', 'Employee')),
    full_name   text,
    user_id     uuid REFERENCES auth.users(id), -- Linked after first login or manual creation
    is_active   boolean DEFAULT true,
    created_at  timestamptz DEFAULT now(),
    created_by  uuid REFERENCES auth.users(id)
);

-- Enable RLS
ALTER TABLE public.staff_keys ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins can manage staff keys" ON public.staff_keys FOR ALL USING (public.is_admin());
CREATE POLICY "Public can check key" ON public.staff_keys FOR SELECT USING (true);

-- 2. UPDATE USER ROLES
-- Add key reference to user_roles
ALTER TABLE public.user_roles ADD COLUMN IF NOT EXISTS login_key text;

-- 3. HELPER FOR ADMIN
-- Note: User 'digital' should be created in Supabase Auth with email 'digital@crm.com'
-- and password '246810235711'. This SQL ensures they have the Admin role.
-- INSERT INTO public.user_roles (user_id, role, full_name, email)
-- SELECT id, 'Admin', 'Digital Admin', 'digital@crm.com' FROM auth.users WHERE email = 'digital@crm.com'
-- ON CONFLICT (user_id) DO UPDATE SET role = 'Admin';
